In [1]:
import pandas as pd

In [2]:
imdb = pd.read_csv('imdb_titles.tsv',sep='\t')
netflix = pd.read_csv('netflix_titles.csv')
ratings = pd.read_csv('ratings.tsv',sep='\t')

C:\Users\dhyey\AppData\Local\Temp\ipykernel_19796\4102194071.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  imdb = pd.read_csv('imdb_titles.tsv',sep='\t')

In [3]:
imdb

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short
...,...,...,...,...,...,...,...,...,...
11601724,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,\N,\N,Drama
11601725,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,Drama
11601726,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,Drama
11601727,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
11601728,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [4]:
imdb.drop(['tconst', 'titleType', 'originalTitle', 'isAdult', 'endYear', 'runtimeMinutes', 'genres'], axis=1)

                       primaryTitle startYear
0                        Carmencita      1894
1            Le clown et ses chiens      1892
2                      Poor Pierrot      1892
3                       Un bon bock      1892
4                  Blacksmith Scene      1893
...                             ...       ...
11601724              Episode #3.17      2009
11601725              Episode #3.19      2010
11601726              Episode #3.20      2010
11601727                   The Wind      2015
11601728  Horrid Henry Knows It All      2014

[11601729 rows x 2 columns]

In [5]:
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [6]:
netflix = netflix.drop(['show_id', 'type', 'director', 'cast', 'country', 'rating', 'duration', 'listed_in', 'description'], axis=1)

In [7]:
ratings

            tconst  averageRating  numVotes
0        tt0000001            5.7      2148
1        tt0000002            5.5       291
2        tt0000003            6.5      2184
3        tt0000004            5.3       187
4        tt0000005            6.2      2931
...            ...            ...       ...
1559469  tt9916846            5.8         6
1559470  tt9916848            5.8         6
1559471  tt9916850            5.8         6
1559472  tt9916852            5.8         6
1559473  tt9916880            7.7        10

[1559474 rows x 3 columns]

In [8]:
imdb_ratings = pd.merge(imdb, ratings, on='tconst', how='inner')

In [9]:
imdb_ratings = imdb_ratings.drop(['tconst', 'titleType', 'originalTitle', 'isAdult', 'endYear', 'runtimeMinutes', 'genres'], axis=1)

In [10]:
imdb_ratings['primaryTitle_clean'] = imdb_ratings['primaryTitle'].str.lower().str.strip()
netflix['title_clean'] = netflix['title'].str.lower().str.strip()

In [11]:
imdb_no_dup = imdb_ratings.sort_values('numVotes', ascending=False).drop_duplicates(subset='primaryTitle_clean') # Remove duplicates, keep instance with greatest number of votes.

In [12]:
netflix_titles = pd.merge(imdb_no_dup, netflix, left_on='primaryTitle_clean', right_on='title_clean', how='inner')

In [32]:
netflix_titles['date_added'] = merged['date_added'].str.strip()
netflix_titles['date_added'] = pd.to_datetime(merged['date_added'], errors='coerce')

In [34]:
netflix_titles

,primaryTitle,startYear,averageRating,numVotes,primaryTitle_clean,title,date_added,release_year,title_clean
0,Inception,2010,8.8,2674083,inception,Inception,2021-08-01,2010,inception
1,Pulp Fiction,1994,8.9,2327728,pulp fiction,Pulp Fiction,2019-01-01,1994,pulp fiction
2,Breaking Bad,2008,9.5,2316546,breaking bad,Breaking Bad,2013-08-02,2013,breaking bad
3,The Matrix,1999,8.7,2148843,the matrix,The Matrix,2019-11-01,1999,the matrix
4,The Lord of the Rings: The Return of the King,2003,9.0,2071611,the lord of the rings: the return of the king,The Lord of the Rings: The Return of the King,2020-01-01,2003,the lord of the rings: the return of the king
...,...,...,...,...,...,...,...,...,...
7430,Posesif,2023,8.0,6,posesif,Posesif,2020-01-01,2017,posesif
7431,Miss Culinary,2019,7.4,5,miss culinary,Miss Culinary,2019-11-19,2019,miss culinary
7432,Death Can Wait,2011,7.8,5,death can wait,Death Can Wait,2020-05-02,2020,death can wait
7433,Wonho Chung: Live in New York,2014,6.0,5,wonho chung: live in new york,Wonho Chung: Live in New York,2020-09-11,2014,wonho chung: live in new york
7434,The Lovers and the Despot,2016,7.2,5,the lovers and the despot,The Lovers and the Despot,2017-02-23,2016,the lovers and the despot